### PR TITLE
Remove useless code

### PR DESCRIPTION
**Pull request by Emmanuel-Nau**

### CODE REVIEW

**Comment by fgalan** [comment]
Has https://github.com/telefonicaid/iotagent-ul/ the same problem? Maybe it has been also fixed in a PR?

**Comment by fgalan** [comment]
Btw, unit tests seem to be failing. That needs to be investigated and fixed before this PR gets merged.

**Comment by Emmanuel-Nau** [comment]
Yes the tests are failing, but I think it was the case before this PR. For sure, we cannot merge this while it's failing. 
In iotagent-ul, the code is different and it is usefull.
Maybe you want to check this first, to make the change on this agent in place of juste removing the code ?

**Comment by Emmanuel-Nau** [comment]
Ok, I think I saw what the problem is. 
The tests behave like they should, and they are proven this code is not useless! 
In fact it is just the use of the dataWithTimeStampArr that seems useless.
Because timeStampData is a reference to a measure object in the payload array, it's modification (adding the timestamp attribute) is reflected in the payload. 
So, I will update my code to only remove the dataWithTimeStampArr if you do not planned to use it. 
Sorry for my misreading of the code.

**Comment by AlvaroVega** [comment]
Now it seems equivalent to:
https://github.com/telefonicaid/iotagent-ul/blob/1fbcff24dd7dc68e25b914c9805caa214715b8fe/lib/bindings/HTTPBindings.js#L96-L104

**Review by AlvaroVega — APPROVED** [review]
LGTM but changelog should be updated

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
