### PR TITLE
REMOVE obsolete iotaJsonTester binary

### PR DESCRIPTION
**Pull request by fgalan**

### CODE REVIEW

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Comment by AlvaroVega** [comment]
@fgalan I guess this doc https://github.com/telefonicaid/iotagent-json/blob/master/docs/stepbystep.md#using-the-command-line-clients should be removed

**Comment by fgalan** [comment]
> @fgalan I guess this doc https://github.com/telefonicaid/iotagent-json/blob/master/docs/stepbystep.md#using-the-command-line-clients should be removed

Right. I'll take care of it (and check if IOTA-UL has a similar one)

**Comment by fgalan** [comment]
> > @fgalan I guess this doc https://github.com/telefonicaid/iotagent-json/blob/master/docs/stepbystep.md#using-the-command-line-clients should be removed
> 
> Right. I'll take care of it (and check if IOTA-UL has a similar one)

PR https://github.com/telefonicaid/iotagent-json/pull/638

**Pull request merged**
