### PR TITLE
update dockerfile to mount a local configuration file

### PR DESCRIPTION
**Pull request by mblaettler**
Move the config.js file in a separate config directory. This makes
it possible to mount a local configuration file.

### CODE REVIEW

**Comment by AlvaroVega** [comment]
I think this kind of feature should be optional (activated by a var en Dockerfile) an disabled by default.

**Comment by mblaettler** [comment]
It is optional. If no volume is mounted (no `-v` flag passed), nothing will change. The default configuration, which is part of the repository, will be used. It's the same behaviour in other containers (e.g. [mosquitto](https://github.com/eclipse/mosquitto/tree/master/docker/1.4.12) or [influxdb](https://github.com/influxdata/influxdata-docker/tree/master/influxdb/1.4))

I can clarify this in the documentation if you'd like.

**Comment by mblaettler** [comment]
I updated the documentation to clarify that the configuration is optional.

**Comment by fgalan** [comment]
Not sure if I'm understanding this fully and correctly but I think the solution should be focused in enhance with new variables `cygnus-entrypoint.sh`, intead that touching Dockefile.

For instance, let's consider:

```
cygnus-ngsi.sources.http-source.port = 5050 
```

A env var should be defined for that (e.g. CYGNUS_HTTP_SOURCE_PORT although @AlvaroVega could provide an alternative name if that is not correct).

Then, `cygnus-entrypoint.sh` would add a check for that variable and adjust the resulting agents.conf file properly, e.g:

```
    if [ "$CYGNUS_HTTP_SOURCE_PORT" != "" ]; then
        sed -i '/#'${CYGNUS_AGENT_NAME}'.sources.http-source.port/c '${CYGNUS_AGENT_NAME}'.sources.http-source.port = '${CYGNUS_HTTP_SOURCE_PORT} ${FLUME_HOME}/conf/${AGENT_CONF_FILE}
fi
```

@AlvaroVega could provide aditional info if needed (e.g. documentation aspects, if any) or if I'm totatlly wrong :)

**Comment by fgalan** [comment]
(Ignore my last comment -now deleted. It was related with another issue and it has been moved)

**Comment by dcalvoalonso** [comment]
I think that this PR is already covered by the recently merged https://github.com/telefonicaid/iotagent-json/pull/337

What do you think?

**Comment by fgalan** [comment]
I agree.

@mblaettler what do you think? Can we close this PR?

**Comment by mblaettler** [comment]
Looks good. Although I'm not sure if the solution provided in #337 could also be applied to a kubernetes deployment specification (with using a config-map).

But in my opinion, the issue can be closed.

**Pull request closed without merging**
