### PR TITLE
Update createBidirectionalDevice.json

### PR DESCRIPTION
**Pull request by AlvaroVega**
introduced by https://github.com/telefonicaid/iotagent-json/pull/522/
and fixed by https://github.com/telefonicaid/iotagent-node-lib/pull/1014

### CODE REVIEW

**Review by fgalan — APPROVED** [review]
LGTM

**Comment by jason-fox** [comment]
You may want to hold back on this and apply https://github.com/telefonicaid/iotagent-node-lib/pull/1020 instead.

**Comment by AlvaroVega** [comment]
> You may want to hold back on this and apply [telefonicaid/iotagent-node-lib#1020](https://github.com/telefonicaid/iotagent-node-lib/pull/1020) first instead to confirm the revert has worked as expected.

I guess new flag will not apply by default, so these tests need to be updated any way.

**Comment by jason-fox** [comment]
@AlvaroVega - Yes the test expectation will need to be changed anyway. I just want to check that my PR doesn't revert back your one again.

**Comment by fgalan** [comment]
> You may want to hold back on this and apply [telefonicaid/iotagent-node-lib#1020](https://github.com/telefonicaid/iotagent-node-lib/pull/1020) first instead to confirm the revert has worked as expected.

Discussion on https://github.com/telefonicaid/iotagent-node-lib/pull/1020 is on the way so maybe it takes a time to merge it. I'd suggest not wait for it.

**Pull request merged**
