### PR TITLE
Updating devDependencies

### PR DESCRIPTION
**Pull request by jason-fox**
Updating the `package.json` dev dependencies.

```diff
   "devDependencies": {
-    "coveralls": "~3.0.2",
-    "husky": "~1.1.0",
-    "istanbul": "~0.4.5",
-    "eslint": "~5.16.0",
-    "eslint-config-tamia": "~6.2.1",
-    "eslint-plugin-prettier": "~3.1.0",
-    "lint-staged": "~7.3.0",
-    "mocha": "5.2.0",
-    "nock": "10.0.2",
-    "prettier": "~1.14.2",
-    "proxyquire": "2.1.0",
-    "remark-cli": "~6.0.1",
-    "remark-preset-lint-recommended": "~3.0.2",
-    "moment": "~2.22.2",
-    "textlint": "~11.0.1",
+    "coveralls": "~3.1.0",
+    "husky": "~4.2.5",
+    "eslint": "~7.5.0",
+    "eslint-config-tamia": "~7.2.5",
+    "eslint-plugin-prettier": "~3.1.4",
+    "lint-staged": "~10.2.11",
+    "mocha": "8.0.1",
+    "nock": "13.0.3",
+    "nyc": "~15.1.0",
+    "prettier": "~2.0.5",
+    "proxyquire": "2.1.3",
+    "remark-cli": "~8.0.1",
+    "remark-preset-lint-recommended": "~4.0.1",
+    "moment": "~2.27.0",
+    "textlint": "~11.7.6",
     "textlint-rule-common-misspellings": "~1.0.1",
-    "textlint-rule-no-dead-link": "~4.4.1",
-    "textlint-rule-terminology": "~1.1.30",
+    "textlint-rule-no-dead-link": "~4.7.0",
+    "textlint-rule-terminology": "~2.1.4",
     "textlint-rule-write-good": "~1.6.2",
     "should": "13.2.3",
     "watch": "~1.0.2"
}
```

### CODE REVIEW

**Comment by jason-fox** [comment]
Related: https://github.com/telefonicaid/iotagent-ul/pull/434

**Comment by jason-fox** [comment]
Looks like [mqtt.org](https://www.isitdownrightnow.com/mqtt.org.html) is currently down. If this continues the link will need to be updated.

**Review by fgalan — APPROVED** [review]
LGTM

**Comment by jason-fox** [comment]
Fixed d0ad85d

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
