### PR TITLE
Add docker image for debugging

### PR DESCRIPTION
**Pull request by AlvaroVega**
Including node inspection

Extend works from https://github.com/telefonicaid/iotagent-json/pull/485 done by @jason-fox

### CODE REVIEW

**Comment by fgalan** [comment]
Should the hook files in https://github.com/telefonicaid/iotagent-json/tree/master/docker/hooks be modified to take into account this new image (unsure)?

**Comment by fgalan** [comment]
Btw, I understand that a "mirror" PR should be done in IOTA-UL repo.

**Comment by jason-fox** [comment]
Can you explain the reason a separate `debug` image is required. Is there any reason you couldn't just override the existing environment variable e.g.:

```console
docker pull iotagent-json
docker run iotagent-json -e NODE_ENV=development
```

If you really, really need to do this, the **default** Node Slim image should be the final image built so that this still works:
 
```console
docker build -t telefonicaiot/iotagent-json .
```

Even better would be to use a build  argument and pass it into the distroless and pm2 builds as well so that all base images can be built with debug or production.


```Dockerfile

ARG NODE_ENV=production

... etc

FROM node:${NODE_VERSION}-slim AS slim
ARG GITHUB_ACCOUNT
ARG GITHUB_REPOSITORY
ARG NODE_ENV

... etc

USER node
ENV NODE_ENV=${NODE_ENV}
```

The `docker/hooks/build` could easily rebuild your variants using cached layers and the build time for a user running the file directly wouldn't increase **at all**.


```console
docker build -t telefonicaiot/iotagent-json:debug . -build-arg NODE_ENV=development
docker push telefonicaiot/iotagent-json:debug
```

**Comment by AlvaroVega** [comment]
@jason-fox debug image is using `--inspect-brk` node arg, that's the reason that I've see to do it. 
Anyway how can I use `--inspection` with a production env like, latest, distroless o pm2 image?

**Comment by jason-fox** [comment]
Just add parameters to override the default `CMD` after the name of the image:


```console
docker run --name debug  telefonicaiot/iotagent-json node --inspect-brk=0.0.0.0 /opt/iotagent-json/bin/iotagent-json --  config.js
```

```text
Unable to find image 'telefonicaiot/iotagent-json:latest' locally
latest: Pulling from telefonicaiot/iotagent-json
8aff230071c9: Already exists 
11e9dbd0ef22: Already exists 
a4382e503884: Already exists 
7e969fceb79f: Already exists 
a54d76effca2: Already exists 
c676cf6b127f: Pull complete 
Digest: sha256:60530d8ceb4788847321cba76525c46cc7e57e3acfb68c1558819b541fd8e15e
Status: Downloaded newer image for telefonicaiot/iotagent-json:latest
Debugger listening on ws://0.0.0.0:9229/0f4c11b2-ba62-4775-ab64-f5ba3391d0fa
For help, see: https://nodejs.org/en/docs/inspector
```

or use the `command` attribute in a docker-compose

**Comment by AlvaroVega** [comment]
Ok @jason-fox works to me without a new image. By the way, pm2 equivalent image could be achieve using this same solution. Thanks!

**Pull request closed without merging**
