### PR TITLE
FIX from MongoDB 3.6 to MongoDB 4.2

### PR DESCRIPTION
**Pull request by fgalan**

### CODE REVIEW

**Comment by fgalan** [comment]
This is also interesting... https://github.com/telefonicaid/iotagent-json/pull/515/checks?check_run_id=1475524456

imagen

It is not actually dead, but it seems that some kind of capping has been reached. That's weird because I understand that both the client (running in github actions infrastructure) and the link (github.com service) are both internal traffic from github point of view but... who knows.

Does this make any sense to you @jason-fox ?

**Comment by jason-fox** [comment]
Unfortunately`textlint-rule-no-dead-link` isn't very configurable, and has a tendency to give false positives (i.e. flagging dead links that aren't dead). Personally I have been removing it from the FIWARE repositories as it give much benefit in its current form.

#### Package.json

```diff
"devDependencies": {
    ...
    "textlint": "~11.7.6",
-   "textlint-rule-no-dead-link": "~4.7.0",
  }
```

#### .textlintrc

```diff
-    "no-dead-link": {
-       "ignoreRedirects": true,
-       "ignore": [
-          "mailto:*",
-          "https://github.com/telefonicaid/sigfox-iotagent/blob/master/doc/roadmap.md",
-          "https://coveralls.io/**"
-     ]
-    }
```

**Comment by fgalan** [comment]
> 
> 
> Unfortunately`textlint-rule-no-dead-link` isn't very configurable, and has a tendency to give [false positives](https://github.com/textlint-rule/textlint-rule-no-dead-link/issues) (i.e. flagging dead links that aren't dead). Personally I have been removing it from the FIWARE repositories as it doesn't give much benefit in its current form.
> #### Package.json
> 
> ```diff
> "devDependencies": {
>     ...
>     "textlint": "~11.7.6",
> -   "textlint-rule-no-dead-link": "~4.7.0",
>   }
> ```
> 
> #### .textlintrc
> 
> ```diff
> -    "no-dead-link": {
> -       "ignoreRedirects": true,
> -       "ignore": [
> -          "mailto:*",
> -          "https://github.com/telefonicaid/sigfox-iotagent/blob/master/doc/roadmap.md",
> -          "https://coveralls.io/**"
> -     ]
> -    }
> ```

Applied to master (through PR https://github.com/telefonicaid/iotagent-json/pull/516), then resync this PR branch. It appears to be solved. Thanks!

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Pull request merged**
