### PR TITLE
FIX unalignemd mocks to fix broken unit test

### PR DESCRIPTION
**Pull request by fgalan**
Maybe the cause is due to PR https://github.com/telefonicaid/iotagent-node-lib/pull/697 ? I have adjusted the mocks, but not fully sure the fix is ok...

Please review @AlvaroVega @dcalvoalonso

### CODE REVIEW

**Comment by dcalvoalonso** [comment]
Maybe I am missing something but I don't understand how this is working now:
- A new group / configuration is provisioned including `cbHost` set to `http://unexistentHost:1026` and `apikey` set to `KL223HHV8732SFL1`:
```
{
    "services": [
        {
            "resource": "/iot/json",
            "apikey": "KL223HHV8732SFL1",
            "entity_type": "TheLightType",
            "trust": "8970A9078A803H3BL98PINEQRW8342HBAMS",
            "cbHost": "http://unexistentHost:1026",
            "commands": [],
            "lazy": [],
            "attributes": [
                {
                    "name": "status",
                    "type": "Boolean"
                }
            ],
            "static_attributes": []
        }
    ]
}
```
- An unprovisioned device sends a measurement using an HTTP POST request and `apiKey` `KL223HHV8732SFL1`:

```
time=2018-11-29T14:33:51.548Z | lvl=DEBUG | corr=ede25ada-c92d-46df-8e22-64b9e6555982 | trans=ede25ada-c92d-46df-8e22-64b9e6555982 | op=IOTASON.HTTP.Binding | srv=n/a | subsrv=n/a | msg=Parsed data: [{"humidity":"32","temperature":"87"}] | comp=IoTAgent
time=2018-11-29T14:33:51.557Z | lvl=DEBUG | corr=ede25ada-c92d-46df-8e22-64b9e6555982 | trans=ede25ada-c92d-46df-8e22-64b9e6555982 | op=IOTASON.HTTP.Binding | srv=n/a | subsrv=n/a | msg=Processing multiple HTTP measures for device [MQTT_UNPROVISIONED] with apiKey [KL223HHV8732SFL1]
```
- The device is registered in the Context Broker but using the host `192.168.1.1`:

```
{
    "url": "http://192.168.1.1:1026/v1/updateContext",
    "method": "POST",
    "json": {
        "contextElements": [
            {
                "type": "TheLightType",
                "isPattern": "false",
                "id": "TheLightType:MQTT_UNPROVISIONED",
                "attributes": [
                    {
                        "name": "status",
                        "type": "Boolean",
                        "value": " "
                    }
                ]
            }
        ],
        "updateAction": "APPEND"
    },
    "headers": {
        "fiware-service": "smartGondor",
        "fiware-servicepath": "/gardens",
        "fiware-correlator": "ede25ada-c92d-46df-8e22-64b9e6555982"
    }
}
```
- The device attributes are updated in the CB using the host of the group:

```
{
    "url": "http://unexistentHost:1026/v1/updateContext",
    "method": "POST",
    "headers": {
        "fiware-service": "smartGondor",
        "fiware-servicepath": "/gardens"
    },
    "json": {
        "contextElements": [
            {
                "type": "TheLightType",
                "isPattern": "false",
                "id": "TheLightType:MQTT_UNPROVISIONED",
                "attributes": [
                    {
                        "name": "humidity",
                        "type": "string",
                        "value": "32"
                    },
                    {
                        "name": "temperature",
                        "type": "string",
                        "value": "87"
                    }
                ]
            }
        ],
        "updateAction": "UPDATE"
    }
}
```

**Comment by dcalvoalonso** [comment]
BTW, sorry for the delay providing feedback... I have been travelling for two weeks! :S

**Comment by dcalvoalonso** [comment]
@AlvaroVega @fgalan https://github.com/telefonicaid/iotagent-node-lib/pull/721 should fix some of the problems I explained in https://github.com/telefonicaid/iotagent-json/pull/353#issuecomment-442858364

**Comment by fgalan** [comment]
@dcalvoalonso thanks for the fixes in the library repository. Test in this PR has broken as a consequence. I'll try to fix it.

**Comment by fgalan** [comment]
Overpassed by PR https://github.com/telefonicaid/iotagent-json/pull/354. At the end, I has been easier fix from master than fixing this PR.

**Pull request closed without merging**
