### PR TITLE
Add curl and tar tool inside all docker telefonicaid objects

### PR DESCRIPTION
**Pull request by Keshav-NEC**
Fix for issue #600.

- This PR give support for curl and tar tools inside Dockerfie.

### CODE REVIEW

**Comment by AlvaroVega** [comment]
@Keshav-NEC thanks for your contribution!
curl is used by https://github.com/telefonicaid/iotagent-json/blob/5483884a46cfb70a40dd9b6bf508c171f7d9d191/docker/Dockerfile#L73 but tar ?

**Comment by Keshav-NEC** [comment]
> @Keshav-NEC thanks for your contribution! curl is used by
> 
> https://github.com/telefonicaid/iotagent-json/blob/5483884a46cfb70a40dd9b6bf508c171f7d9d191/docker/Dockerfile#L73
> 
> but tar ?

Hi @AlvaroVega, support for tar was added in dockerfile because it was mentioned in issue. Thanks.

**Comment by AlvaroVega** [comment]
curl and tar tools are probably dependencies of other packages.
The issue https://github.com/telefonicaid/iotagent-json/issues/600 is wrong addressed from the beginning.

**Comment by fgalan** [comment]
Having closed issue #600, I'd suggest to close this PR.

@Keshav-NEC what do you think?

**Comment by Keshav-NEC** [comment]
PR closed as per comment received.

**Pull request closed without merging**
