### PR TITLE
FIX broken unit test due to mock failing with ?type expecations

### PR DESCRIPTION
**Pull request by fgalan**
Please @dcalvoalonso have a look.

### CODE REVIEW

**Comment by dcalvoalonso** [comment]
Maybe we should add a CNR entry?

**Comment by dcalvoalonso** [comment]
For the rest, LGTM

**Comment by fgalan** [comment]
> Maybe we should add a CNR entry?

This is a new feature in the library, so the CNR entry should be (and actually is) there, see
https://github.com/telefonicaid/iotagent-node-lib/blob/master/CHANGES_NEXT_RELEASE#L5

**Comment by dcalvoalonso** [comment]
Ok, NTC then.

**Pull request merged**
