### PR TITLE
Thinking thing module removal

### PR DESCRIPTION
**Pull request by mapedraza**
Removing Thinking Thing plugin

### CODE REVIEW

**Comment by mapedraza** [comment]
In this PR this is the only reference to Thinking Things (based on comments): https://github.com/telefonicaid/iotagent-json/blob/task/remove-thinking-thing/lib/timestampProcessPlugin.js

It is only used by Thinking Thing modules?

**Comment by fgalan** [comment]
> It is only used by Thinking Thing modules?

It seems so. JavaDoc comment explicitly mentions Thining Thing

> Looks for Thinking Thing modules and parses them, updating the entity with the transformed value.

So I'd suggest to remove also that file. @AlvaroVega what do you think?

**Comment by AlvaroVega** [comment]
That file https://github.com/telefonicaid/iotagent-json/blob/task/remove-thinking-thing/lib/timestampProcessPlugin.js seems no used by any module. It seems that was modev into iota-node-lib under https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/plugins/timestampProcessPlugin.js

So can be removed

**Comment by fgalan** [comment]
We are currently researching the mysterious decrease of -0.9 coverage... It seems it is related with the following 3 uncovered lines in binding/MQTTBinding.js

imagen

**Comment by fgalan** [comment]
After merging master into this PR (which supposely no code changes= coverage changes to -0.7%

Report https://coveralls.io/builds/41333541

imagen

Looking to the report, we see a decrease in lib/ but not which specific file decrease is causing it (in others words, a "arrow down" in lib/ but no "arrow down" in any file)

imagen

I don't know hoy to interpret this results :O

**Comment by fgalan** [comment]
...and after fixing a typo in CNR file (which doesn't touch any code) in commit 1082a3b coverage goes back to "successful". Report https://coveralls.io/builds/41329119, showing +0.04%

It seem we have some king of glitch out there... but let's move forward, merging this PR and attempting to fix it in the future if needed.

**Comment by fgalan** [comment]
Mabye the -0.7% drop is due to lib/iotagent-json.js modifications in this PR: 3 covered lines has been removed in this PR, so the coverage is expected to drop.

PR ready for merging.

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
