### PR TITLE
the same fix for http, mqtt and amqp bindings

### PR DESCRIPTION
**Pull request by AlvaroVega**
continuation of PR https://github.com/telefonicaid/iotagent-json/pull/762
Using the same CNR entry

### CODE REVIEW

**Comment by fgalan** [comment]
Need of twin PR in IOTA-UL?

**Comment by AlvaroVega** [comment]
> Need of twin PR in IOTA-UL?

twin PR https://github.com/telefonicaid/iotagent-ul/pull/638

**Review by fgalan — APPROVED** [review]
LGTM

**Review by mapedraza — APPROVED** [review]
LGTM

**Pull request merged**
